#!/usr/bin/env bash

source "$(dirname $0)/../dokku_common"

ARAWAK_REPOSITORY="https://github.com/heroku/node-js-sample"

case "$1" in

  arawak:install)
    verify_app_name "$2"
    verify_max_args 2 "$@"

    info "Creating application..."

    dokku create "$APP"
    info "Clonning sources into $APP_DIR..."

    cd "$APP_DIR"
    git fetch "$ARAWAK_REPOSITORY"

    info "Creating database..."

    dokku mongodb:create "$APP"
    dokku mongodb:link "$APP" "$APP"

    info "Creating environment variables..."
    dokku config:set "$APP" "NODE_ENV=production"

    info "Building application..."

    dokku rebuild "$APP"
    info "Everything is done!"

    ;;

  arawak:remove)

    verify_app_name "$2"
    verify_max_args 2 "$@"

    dokku mongodb:delete "$APP"
    dokku delete "$APP"

    ;;

  help)
    cat && cat<<EOF
    arawak:install <app>       Create application
    arawak:remove <app>        Remove appliccation
EOF   
  ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;
esac
