#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$(dirname $0)/../dokku_common"

ARAWAK_REPOSITORY="https://github.com/arawak-io/cashew"

case "$1" in
  arawak:deploy)

    verify_max_args 2 "$@"
    check_app_name "$2"


    info "Creating application..."

    dokku create "$APP"
    info "Clonning sources into $APP_DIR..."

    cd "$APP_DIR"
    git fetch "$ARAWAK_REPOSITORY"

    info "Creating database..."

    dokku mongodb:create "$APP"
    dokku mongodb:link "$APP" "$APP"

    info "Creating environment variables..."
    # dokku config:set "$APP" "NODE_ENV=production"
    echo "export NODE_ENV=production" > "$APP_DIR/ENV"

    info "Building application..."

    # dokku rebuild "$APP"

    HEAD="$(git rev-parse "FETCH_HEAD")"
    dokku rebuild "$APP" "$HEAD"
    echo "$HEAD" > "refs/heads/master"


    info "Everything is done!"
    ;;

  arawak:remove)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    dokku mongodb:delete "$APP"
    dokku delete "$APP"
	;;

  help)
    cat && cat<<EOF
    arawak:deploy <app>        Create application
    arawak:remove <app>        Remove appliccation
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;
esac
